import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { pinyin } from 'pinyin'
import { PINYIN_DB } from '../src/data/pinyinDb.js'

function normalize(value) {
  return value
    .toLowerCase()
    .replaceAll('ü', 'v')
    .replaceAll('u:', 'v')
    .replace(/[^a-z]/g, '')
}

const entries = PINYIN_DB.map(question => {
  const syllables = pinyin(question.content, { style: 'normal', segment: true })
    .flat()
    .map(normalize)

  let syllableIndex = 0
  const groups = question.chars.map(char => {
    const generated = syllables.slice(syllableIndex, syllableIndex + [...char.char].length).join('')
    const curated = normalize(char.pinyin)
    syllableIndex += [...char.char].length
    // The database pronunciation is curated for polyphonic characters in context.
    if (!curated) return generated
    return !generated || generated !== curated ? curated : generated
  })

  return [question.content, groups]
})

const output = `// This file is generated by npm run generate:pinyin. Do not edit manually.\n` +
  `export const FULL_PINYIN_MAP = ${JSON.stringify(Object.fromEntries(entries), null, 2)}\n`

const outputUrl = new URL('../src/data/generatedFullPinyin.js', import.meta.url)
await writeFile(fileURLToPath(outputUrl), output)
